# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='headshot',
            field=models.ImageField(upload_to='C:/Users/aislam/DjangoProjects/mysite/tmp'),
        ),
    ]
